# fly.toml app configuration file generated for stronamajlitechawww on 2023-08-05T17:06:48+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "stronamajlitechawww"
primary_region = "waw"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
