name: Deploy website
on:
  workflow_dispatch:

jobs:
  inline:
    name: Deploy website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install flyctl
        run: curl -L https://fly.io/install.sh | sh
      - name: Deploy to frontend
        run: flyctl deploy
        env:
            FLY_API_TOKEN: ${{secrets.SURGE_EMAIL}}
