name: Deploy website
on:
  workflow_dispatch:

jobs:
  inline:
    name: Deploy website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "*"
      - name: Deploy to frontend
        run: npx --no-install surge --project src --domain majlitech.pl
        env:
            SURGE_LOGIN: ${{secrets.SURGE_EMAIL}}
            SURGE_TOKEN: ${{secrets.SURGE_TOKEN}}
